dependencies:
  - smartcontractkit/chainlink-brownie-contracts@1.1.1
compiler:
  solc:
    version: 0.6.6
    remappings:
      - "@chainlink=smartcontractkit/chainlink-brownie-contracts@1.1.1"
# dotenv: .env
networks:
  mainnet-fork:
    eth_usd_price_feed: "0x5f4eC3Df9cbd43714FE2740f5E3616155c5b8419"
